### ISSUE TITLE
In mobile not work

### ISSUE THREAD

**Issue by josejachuf** [Esurnir/vue2-leaflet-freedraw#1]
Hello

First of all, thank you very much for your work .
I am using this component in a project, it works fine on desktop, but I can not draw on mobile devices or in the desktop browser using mobile mode.

It has happened to you or is something that I am doing wrong 

Jose

**Comment by Esurnir** [comment]
Hi, leaflet-freedraw unfortunately doesn't seem to support mobile drawings (tested on iOS using this [demo](http://freedraw.herokuapp.com/)). I advise opening an issue with [leaflet-freedraw](https://github.com/Wildhoney/Leaflet.FreeDraw) for mobile support. I'm just wrapping around Wildhoney's code in a vue2-leaflet compatible manner.

**Comment by Esurnir** [comment]
I personally would advise disabling the vue component (I think a v-if would work, another way is setting the mode to NONE or 0) if you detect you're in a mobile environment. But right now the underlying "drawing capture" isn't handling touch events it seems.

**Comment by josejachuf** [comment]
Hi @Esurnir , thanks for the answer.

After I sent here I went to xxxx and saw that there were already several similar reports 

> I personally would advise disabling the vue component (I think a v-if would work, another way is setting the mode to NONE or 0) if you detect you're in a mobile environment. But right now the underlying "drawing capture" isn't handling touch events it seems.

I'm doing it, if it's in mobile disabled the drawing 

Jose

**Comment by josejachuf** [comment]
https://github.com/Wildhoney/Leaflet.FreeDraw/issues/171
https://github.com/Wildhoney/Leaflet.FreeDraw/issues/161
https://github.com/Wildhoney/Leaflet.FreeDraw/issues/155
https://github.com/Wildhoney/Leaflet.FreeDraw/issues/3

**Comment by Esurnir** [comment]
Have you tried "tap: true" as a leaflet map option when mobile ? Something I found while googling. I believe you can pass the option as a :options="mapOptions" with map options an object containing that. Or something similar.
